name: Testing and build Docker container
on:
  push:
    branches-ignore:
      - dev
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx --version
          pipx install poetry
          poetry --version

      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry install --with test

      - name: Testing with pytest
        run: poetry run pytest

  # TODO: добавить сборку проекта в контейнер и тестирование контейнера
  build_docker_container:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_READ_WRITE_DELETE }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          build-contexts: |
            python=docker-image://python:3.11
          push: true
          tags: my-blockchain:latest

      - name: Inspect
        run: |
          docker image inspect myimage:latest



